### ISSUE TITLE
creaArchivo

### ISSUE THREAD

**Issue by ziggylineous** [sisoputnfrba/ansisop-parser#28]
`abrir f LE /smallFile.bin`    le falta flag C de crear
`a *= 88`   es *a = 88
`escribir f a 10`    podría ser escribir f a 4

**Comment by nicozar95** [comment]
Hola
Gracias por notar los 2 primeros errores!
Con lo de escribir 10 bytes, a nosotros nos interesa que ese archivo escriban lo que corresponda + bytes basura para ver si lo escriben realmente en los bloques y despues poder corroborar el tamaño
